language: ruby
rvm:
  - 2.6.3

cache:
  - bundler
  - /home/travis/.rvm/

services:
  - postgresql

before_script: 
  - bundle install --jobs=3 --retry=3
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create

script:
  â€” bundle exec rspec